In [2]:
import numpy as np

In [8]:
W=np.array([[1,2,3],[3,4,5]])
W.shape
#W.shape[0]

(2, 3)

In [9]:
W.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [11]:
type(W)

numpy.ndarray

In [12]:
type(W.shape)

tuple

In [20]:
M=np.arange(12).reshape(3,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
M[M>4]=-17

array([[  0,   1,   2,   3],
       [  4, -17, -17, -17],
       [-17, -17, -17, -17]])

In [32]:
s=0
for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        s+=M[i,j]
        print(s,',',sep='',end='') # Parameter sep und end über Namen setzen
print(s)
def func(x):
    print(x*x)
    return x
func(3)


0,1,3,6,10,-7,-24,-41,-58,-75,-92,-109,-109
9


3